trigger:
- 'master'

name: 1.0$(Rev:.r)

variables:
  containerRegistryName: 'guestline'
  containerRegistryServiceConnectionName: 'cs sp @ prod1we'
  containerRegistryURL: '$(containerRegistryName).azurecr.io'
  imageName: '$(containerRegistryURL)/$(name):$(Build.BuildNumber)'
  name: 'hello-mark'

jobs:
- job: 'Default'
  pool:
    vmImage: 'ubuntu-16.04'
  
  steps:
  - task: Docker@1
    displayName: 'Build'
    inputs:
      azureSubscriptionEndpoint: '$(containerRegistryServiceConnectionName)'
      azureContainerRegistry: '$(containerRegistryURL)'
      imageName: '$(imageName)'
      command: build
      dockerFile: './src/Dockerfile'
  
  - task: Docker@1
    displayName: 'Push'
    inputs:
      azureSubscriptionEndpoint: '$(containerRegistryServiceConnectionName)'
      azureContainerRegistry: '$(containerRegistryURL)'
      imageName: '$(imageName)'
      command: push
  
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Helm'
    inputs:
      pathtoPublish: 'helm'
      artifactName: 'helm'